### PR TITLE
API Fixes: general save method to update list in database

### LINKED ISSUE #1: API Fixes
Adjust and clean API part (Server and Components as well)

### PR DESCRIPTION
**Pull request by khamui**
close #1

### CODE REVIEW

File: server/server.js [hunk 1]
```diff
@@ -135,9 +141,39 @@ async function putSheetValues(rows) {
       SET sheet_id=${row[1]}, cat_data='${catData}'
       WHERE cat_id=${row[0]};\n\n`);
   }
+  console.log(sql);
```
Comment (khamui) [inline server/server.js]: line used?

File: server/server.js [hunk 2]
```diff
@@ -135,9 +141,39 @@ async function putSheetValues(rows) {
...
+    const catData = JSON.stringify(row.slice(2));
+    sql = sql.concat(
+      `
+      INSERT INTO tbl_hot (sheet_id,cat_data)\n
+      VALUES (${currentSheetId},'${catData}');\n\n`);
+  }
+  return await getFromDatabaseBy(sql);
+}
+
+async function deleteSheetCategory(resource) {
```
Comment (khamui) [inline server/server.js]: function used?

File: server/server.js [hunk 3]
```diff
@@ -135,9 +141,39 @@ async function putSheetValues(rows) {
...
+  const currentSheetId = resource.data[0][1];
```
Comment (khamui) [inline server/server.js]: handle case if 0th element is the new created with null

File: src/editor/sheet-service.ts [hunk 4]
```diff
@@ -35,11 +40,11 @@ export class SheetService {
     };
   } 
 
-  save(resource: IResourcable) {
-    this.api.update('sheets/' + resource['glaId'] + '/' + resource['type'], resource)
-      .then((result) => {
-        // LOGGER return
-      });
+  async save(resource: IResourcable, mode: Mode) {
```
Comment (khamui) [inline src/editor/sheet-service.ts]: mode needed?
